### ISSUE TITLE
won't deploy to heroku with production flag enabled

### ISSUE THREAD

**Issue by mren** [greenkeeper-keeper/reference-instance#121]
Hello, i tried to deploy the reference app to heroku, but the install script failed.

`run-s` is installed as a `devDependency` and won't be installed on heroku.
This can be changed if `NPM_CONFIG_PRODUCTION=false` is set as an environment variable.

Maybe you want to add that to the documentation or move these dependencies from dev to regular ones.

**Comment by travi** [comment]
sorry for missing this one too. it looks like you figured out the approach that i use. im not a huge fan of how you have to jump through hoops for the build steps on heroku, but it is how things work. installing the `devDependencies` is the approach i take, but you're right that it should be documented. i'll get that added soon. 

thanks a lot for the report!
