### ISSUE TITLE
add git tag when hapi-greenkeeper-keeper version changes

### ISSUE THREAD

**Issue by travi** [greenkeeper-keeper/reference-instance#49]
something similar to [this](https://coderwall.com/p/mk18zq/automatic-git-version-tagging-for-npm-modules) should be close to what would be needed.

**Comment by travi** [comment]
@cdaringe since i dont use this through docker, this isn't likely to be a huge priority for me, but it seems like having tagged images on docker hub would be valuable to those who do.

if you and others could help me understand the level of value this would provide, that would be helpful. obviously help thinking through how to make it happen or a PR would help get this in place even sooner

**Comment by cdaringe** [comment]
@travi, you're already doin sem-rel style commits--why not wire in semantic-release?  it handles tagging on its own.    in ampersand-js, we always used this convention, which was pretty good too: https://github.com/AmpersandJS/ampersand-view/blob/master/package.json#L53

...aaaannd after writing all of that, im realizing maybe i misinterpreted the issue.  is the goal to pair up `reference-instances`'s git tags w/ `hapi-greenkeeper-keeper`s, such that there is always 1:1 parity between them?

**Comment by travi** [comment]
Right, i already use semantic release for the happy plugin itself (and most other packages i manage :)). It's a huge help, but i don't think it's a fit in this case. 

Yeah, my intent here was to base the tags for the docker image on the version of the hapi plugin. Certainly let me know if you have a better scheme in mind.

**Comment by travi** [comment]
a few thoughts:
* i think it is possible to get docker hub to tag images based on git tags
* setting a tag from travis during the build is probably the simplest place to do this based on when the hapi plugin get upgraded (maybe something along the lines of how [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile) works )
* does docker hub build git tags in order to apply the image tag, or is a tagged commit necessary?

**Comment by travi** [comment]
`git diff $TRAVIS_COMMIT_RANGE` would give the diff included in a change. would still need to determine if `hapi-greenkeeper-keeper` changed versions and what the new version is.

**Comment by travi** [comment]
could check for existence of a tag for the current version of `hapi-greenkeeper-keeper` with something along the lines of: 
```
git rev-parse v`jq '.dependencies."hapi-greenkeeper-keeper"' -r package.json`
```

**Comment by travi** [comment]
- [x] determine if tag already exists for version of `hapi-greenkeeper-keeper`
- [x] add tag if it doesn't already exist
- [x] push tag to github
- [x] build tags on docker hub and tag image
- [x] only tag on `master`
- [x] document the versioning strategy in the readme
